apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: s-car
  name: deploy02
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: main-container
        image: techwithnc/simpleweb:2.0
        volumeMounts:
          - name: vol01
            mountPath: /var/log/nginx/
        resources:
          limits:
            memory: "32Mi"
            cpu: "100m"
      - name: sidecar-container
        image:  techwithnc/busybox:1.0
        command: ["sh","-c","while true; do cat /tmp/main-app-log/access.log; sleep 30; done"]
        volumeMounts:
          - name: vol01
            mountPath: /tmp/main-app-log
        resources:
          limits:
            memory: "32Mi"
            cpu: "100m"
      volumes:
        - name: vol01
          emptyDir: {}
            
