# Author: "Tech With NC"
#
# Date Created: 1/Feb/2023
# Last Modified: 1/Jun/2023
# 
# Description.
# Kubernetes deployment file for creating init containers.

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: init
  name: deploy03
  labels:
    app: myweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      labels:
        app: myweb
    spec:
      initContainers:
        - name: init-container
          image: techwithnc/busybox:1.0
          command: ['sh', '-c', "until nslookup svc01; do echo waiting for svc01; sleep 20; done"]
      containers:
      - name: main-app
        image: techwithnc/simpleweb:2.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
          requests:
            memory: "128Mi"
            cpu: "100m"
      - name: sidecar-container
        image: techwithnc/busybox:1.0
        command: ["sh", "-c", "sleep 3600"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
          requests:
            memory: "128Mi"
            cpu: "100m"
