apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: e-dir
  name: deploy01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
      - name: myweb
        image: techwithnc/simpleweb:3.0
        command: ["sh", "-c"]
        args:
          - while true;
              do date >> /tmp/emptydir/date.txt;
              sleep 10;
            done
        ports:
          - containerPort: 80
        volumeMounts:
          - name: vol01
            mountPath: /tmp/emptydir
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
      - name: mybusybox
        image: techwithnc/busybox:1.0
        volumeMounts:
          - name: vol01
            mountPath: /tmp/date-from-main
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        command: ["sh", "-c"]
        args:
        - sleep 3000
      volumes:
        - name: vol01
          emptyDir: {}
            
