apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
  namespace: s-car
spec:
  containers:
  - name: myapp
    image: techwithnc/busybox:1.0
    command: ["sh", "-c" , "sleep 3600"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "200m"