# Author: "Tech With NC"
#
# Date Created: 1/Feb/2023
# Last Modified: 1/Jun/2023
# 
# Description.
# Creating sidecar container.

apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
  namespace: s-car
spec:
  containers:
  - name: myapp
    image: techwithnc/busybox:1.0
    command: ["sh", "-c" , "sleep 3600"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "200m"