# Author: "Tech With NC"
#
# Date Created: 1/Feb/2023
# Last Modified: 1/Jun/2023
# 
# Description.
# Creating service in "init" namespace.

apiVersion: v1
kind: Service
metadata:
  name: svc01
  namespace: init
spec:
  selector:
    app: myweb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80