global:
  smtp_smarthost: smtp.gmail.com:587
  smtp_from: ## YOUR_EMAIL_ADDRESS
  smtp_auth_username: ## YOUR_EMAIL_ADDRESS
  smtp_auth_identity: ## YOUR_EMAIL_ADDRESS
  smtp_auth_password: ## YOUR_EMAIL_PASSWORD
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'db-team'
  routes:
  - receiver: 'slack-noti'
    matchers:
    - severity="critical"

receivers:
- name: 'infra-team'
  email_configs:
    - to: ## RECEIVER_EMAIL_ADDRESS
      send_resolved: true
- name: 'db-team'
  email_configs:
    - to: ## RECEIVER_EMAIL_ADDRESS
      send_resolved: true
- name: 'slack-noti'
  slack_configs:
  - api_url: ## YOUR_SLACK_API_URL
    channel: '#alerts'
    send_resolved: true

    icon_url: https://avatars3.githubusercontent.com/u/3380462
    title: |-
      [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
      {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
        {{" "}}(
        {{- with .CommonLabels.Remove .GroupLabels.Names }}
          {{- range $index, $label := .SortedPairs -}}
            {{ if $index }}, {{ end }}
            {{- $label.Name }}="{{ $label.Value -}}"
          {{- end }}
        {{- end -}}
        )
      {{- end }}
    text: >-
      {{ with index .Alerts 0 -}}
        :chart_with_upwards_trend: *<{{ .GeneratorURL }}|Graph>*
        {{- if .Annotations.runbook }}   :notebook: *<{{ .Annotations.runbook }}|Runbook>*{{ end }}
      {{ end }}
      *Alert details*:
      {{ range .Alerts -}}
        *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
      *Description:* {{ .Annotations.description }}
      *Details:*
        {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
        {{ end }}
      {{ end }}