## This is the ansible playbook for prometheus installation on Ubuntu.
---
- name: Prometheus installation on Ubuntu OS
  hosts: all
  become: yes
  tasks:
  - name: APT update.
    ansible.builtin.apt:
      update_cache: yes
  - name: Create user for prometheus.
    ansible.builtin.user:
      name: prometheus
      shell: /bin/false
      create_home: false
  - name: Creates directories.
    ansible.builtin.file:
      path: '{{item}}'
      state: directory
      owner: prometheus
      group: prometheus
    with_items: ["/etc/promethus", "/var/lib/prometheus"]
  - name: Download Original file
    ansible.builtin.get_url:
        url: https://github.com/prometheus/prometheus/releases/download/v2.44.0/prometheus-2.44.0.linux-amd64.tar.gz
        dest: /home/techwithnc/prometheus.tar.gz
        checksum: sha256:be5c8e43618999c3109c1416e04e4ce25c689f82388db6d275a245fe5b1daae7
  - name: unarchive original tar file.
    unarchive:
      src: /home/techwithnc/prometheus.tar.gz
      dest: /home/techwithnc/
      remote_src: yes
  - name: copy file to prometheus dir.
    ansible.builtin.copy:
      src: /home/techwithnc/prometheus-2.44.0.linux-amd64/{{item}}
      dest: /usr/local/bin/
      owner: prometheus
      group: prometheus
      remote_src: yes
    with_items: ["prometheus", "promtool"]
  - name: copy file to /etc/ dir
    ansible.builtin.copy:
      src: /home/techwithnc/prometheus-2.44.0.linux-amd64/{{item}}
      dest: /etc/prometheus/
      owner: prometheus
      group: prometheus
      remote_src: yes
    with_items: ["consoles", "console_libraries"]
  - name: Remove file (delete file)
    ansible.builtin.file:
      path: /home/techwithnc/prometheus.tar.gz
      state: absent
  - name: Recursively remove directory
    ansible.builtin.file:
      path: /home/techwithnc/prometheus-2.44.0.linux-amd64
      state: absent
  - name: create prometheus configuration file.
    ansible.builtin.shell: |
      cat <<EOF | sudo tee /etc/prometheus/prometheus.yml
      global:
        scrape_interval: 15s
      scrape_configs:
        - job_name: 'prometheus'
          scrape_interval: 5s
          static_configs:
            - targets: ['YOUR-IP-ADD:9090']
      EOF
  - name: Change ownership of file and directory.
    ansible.builtin.file:
      path: /etc/prometheus/prometheus.yml
      owner: prometheus
      group: prometheus
  - name: create prometheus service file.
    ansible.builtin.shell: |
      cat <<EOF | sudo tee /etc/systemd/system/prometheus.service
      [Unit]
      Description=Prometheus
      Wants=network-online.target
      After=network-online.target

      [Service]
      User=prometheus
      Group=prometheus
      Type=simple
      ExecStart=/usr/local/bin/prometheus \
          --config.file /etc/prometheus/prometheus.yml \
          --storage.tsdb.path /var/lib/prometheus/ \
          --web.console.templates=/etc/prometheus/consoles \
          --web.console.libraries=/etc/prometheus/console_libraries

      [Install]
      WantedBy=multi-user.target
      EOF
  - name: systemd unit
    ansible.builtin.systemd:
      name: prometheus.service
      daemon_reload: true
      enabled: true
      state: started