---
- name: Node_Exporter installation on Ubuntu OS
  hosts: ubt01
  become: yes
  tasks:
  - name: Create user_node
    ansible.builtin.user:
      name: user_node
      shell: /bin/false
      create_home: false
  - name: Download Original file
    ansible.builtin.get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz
        dest: /home/techwithnc/node_exporter.tar.gz
        checksum: sha256:af999fd31ab54ed3a34b9f0b10c28e9acee9ef5ac5a5d5edfdde85437db7acbb
  - name: unarchive original tar file.
    unarchive:
      src: /home/techwithnc/node_exporter.tar.gz
      dest: /home/techwithnc/
      remote_src: yes
  - name: copy file to /usr/local/bin dir
    ansible.builtin.copy:
      src: /home/techwithnc/node_exporter-1.5.0.linux-amd64/node_exporter
      dest: /usr/local/bin
      owner: user_node
      group: user_node
      mode: '0755'
      remote_src: yes
  - name: Remove file (delete file)
    ansible.builtin.file:
      path: /home/techwithnc/node_exporter.tar.gz
      state: absent
  - name: Recursively remove directory
    ansible.builtin.file:
      path: /home/techwithnc/node_exporter-1.5.0.linux-amd64
      state: absent
  - name: create service file.
    ansible.builtin.shell: |
      cat <<EOF | sudo tee /etc/systemd/system/node_exporter.service
      [Unit]
      Description=Node Exporter
      Wants=network-online.target
      After=network-online.target

      [Service]
      User=user_node
      Group=user_node
      Type=simple
      ExecStart=/usr/local/bin/node_exporter

      [Install]
      WantedBy=multi-user.target
      EOF
  - name: systemd unit
    ansible.builtin.systemd:
      name: node_exporter.service
      daemon_reload: true
      enabled: true
      state: started