# Author: "Tech With NC"
#
# Date Created: 1/Feb/2023
# Last Modified: 1/Jun/2023
# 
# Description.
# kubernetes deployment file for creating container replica in "staging" namespace.

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: staging
  name: deploy
  labels:
    app: myweb01
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myweb01
  template:
    metadata:
      labels:
        app: myweb01
    spec:
      initContainers:
        - name: init
          image: techwithnc/busybox:1.0
          command: ['sh', '-c', "until nslookup svc; do echo waiting for svc in staging namespace; sleep 20; done"]
      containers:
      - name: main-app
        image: techwithnc/simpleweb:2.0
        env:
          - name: COMPANY_NAME
            valueFrom:
              configMapKeyRef:
                key: company-name
                name: mycm
          - name: COMPANY_ADDRESS
            valueFrom:
              configMapKeyRef:
                key: company-address
                name: mycm
          - name: COMPANY_INCOME
            valueFrom:
              secretKeyRef:
                key: income
                name: mysecret
          - name: COMPANY_OWNER
            valueFrom:
              secretKeyRef:
                key: top1-shareholder-name
                name: mysecret
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
          - name: vol01
            mountPath: /home/company-data
      - name: sidecar-container
        image: techwithnc/busybox:1.0
        command: ["sh", "-c", "sleep 3600"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
          requests:
            memory: "128Mi"
            cpu: "100m"
      volumes:
        - name: vol01
          persistentVolumeClaim:
            claimName: pvc
