# Author: "Tech With NC"
#
# Date Created: 1/Feb/2023
# Last Modified: 1/Jun/2023
# 
# Description.
# Creating PersistentVoulume in kubernetes.

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv02
  labels:
    name: pv02
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: scn02
  hostPath:
    path: /tmp/pv02