# Author: "Tech With NC"
#
# Date Created: 1/Feb/2023
# Last Modified: 1/Jun/2023
# 
# Description.
# Creating PersistentVoulumeClaim in "staging" namespace.

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: staging
  name: pvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: scn01
  accessModes:
    - ReadWriteOnce