# Author: "Tech With NC"
#
# Date Created: 1/Feb/2023
# Last Modified: 1/Jun/2023
# 
# Description.
# Creating service in "staging" namespace.


apiVersion: v1
kind: Service
metadata:
  name: svc
  namespace: staging
spec:
  selector:
    app: myweb01
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80