apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: staging
  name: deploy02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: techwithnc/busybox:1.0
        command: ["sh", "-c", "sleep 36000"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        volumeMounts:
          - name: vol01
            mountPath: /home/dir01  
      volumes:
        - name: vol01
          persistentVolumeClaim:
            claimName: pvc03