# Author: "Tech With NC"
#
# Date Created: 1/Feb/2023
# Last Modified: 1/Jun/2023
# 
# Description.
# Kubernetes deployment file for creating container replicas in "staging" namespace.

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: staging
  name: deploy01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: techwithnc/busybox:1.0
        command: ["sh", "-c", "sleep 36000"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        volumeMounts:
          - name: vol01
            mountPath: /home/dir01
          - name: vol02
            mountPath: /home/dir02
      volumes:
        - name: vol01
          persistentVolumeClaim:
            claimName: pvc01
        - name: vol02
          persistentVolumeClaim:
            claimName: pvc02