# Author: "Tech With NC"
#
# Date Created: 1/Feb/2023
# Last Modified: 1/Jun/2023
# 
# Description.
# Creating "staging" namespace in kubernetes.

apiVersion: v1
kind: Namespace
metadata:
  name: staging