# Author: "Tech With NC"
#
# Date Created: 1/Feb/2023
# Last Modified: 1/Jun/2023
# 
# Description.
# Creating PersistentVoulume in kubernetes.

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
  labels:
    name: pv01
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: scn01
  hostPath:
    path: /tmp/pv01