apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dev
  name: pvc04
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: scn04
  accessModes:
    - ReadWriteOnce