# Author: "Tech With NC"
#
# Date Created: 1/Feb/2023
# Last Modified: 1/Jun/2023
# 
# Description.
# Creating PersistentVoulumeClaim in "dev" namespace.

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dev
  name: pvc04
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: scn04
  accessModes:
    - ReadWriteOnce